export const communitiesTable = `
CREATE TABLE IF NOT EXISTS Communities (
community_id VARCHAR(36) PRIMARY KEY,
community_name VARCHAR(50) NOT NULL UNIQUE,
community_image_url VARCHAR(255),
community_desc VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
`;